# Use the official PHP 8.2 image as the base image
FROM php:8.2-fpm

# Install system dependencies and extensions
RUN apt-get update && apt-get install -y \
    libzip-dev \
    unzip \
    && docker-php-ext-configure zip \
    && docker-php-ext-install zip pdo pdo_mysql

# Set the working directory to the Laravel project root
WORKDIR /var/www/html

# Expose port 9000 for PHP-FPM
EXPOSE 9001

# Command to start PHP-FPM
CMD ["php-fpm"]
